name: CI
on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Up ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install Software
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python setup.py install

      - name: Unit Test
        run: pytest -v tests

